apiVersion: v1
kind: Secret
metadata:
  name: genericmed-secrets
  namespace: genericmed-production
  labels:
    app.kubernetes.io/name: genericmed
type: Opaque
stringData:
  JWT_SECRET: "prod_k8s_enterprise_hmac_sha256_genericmed_vault_2026!"
  DATABASE_URL: "postgres://genericmed_app:secure_med_pass_2026@postgres.genericmed-production.svc.cluster.local:5432/genericmed_db"
  REDIS_URL: "redis://redis.genericmed-production.svc.cluster.local:6379"
  KAFKA_BROKERS: "kafka-bootstrap.genericmed-production.svc.cluster.local:9092"
  GEMINI_API_KEY: "AIzaSyProductionVaultKeyPlaceholder"
