apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genericmed.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "genericmed.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | quote }}
